version: '3'
services:
  database:
    restart: always
    image: postgres:12.2
    container_name: colivery-db
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=colivery-db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=d2e5e3e3-4203-472d-8290-e7d10b64fa45

  api:
    image: "registry.gitlab.com/colivery/colivery-api"
    container_name: colivery-api
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - database
    environment:
      - "SERVER_PORT=8080"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/colivery-db"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=d2e5e3e3-4203-472d-8290-e7d10b64fa45"
